app:
    resource: @AppBundle/Controller/
    type:     annotation

gbs_blog:
    resource: "@GbsBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
